FROM ubuntu:noble

ARG TARGETARCH
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=GMT

# Install all required packages
RUN apt-get update \
	&& apt-get install -y --no-install-recommends openjdk-17-jdk wget git gdebi-core \
	    build-essential tzdata ca-certificates p11-kit

RUN python3 -m venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

ENV LANG=C.UTF-8

# Install srcML
RUN if [ "${TARGETARCH}" = "arm64" ]; then \
        wget https://github.com/srcML/srcML/releases/download/v1.1.0/srcml_1.1.0-1_ubuntu24.10_arm64.deb && \
        gdebi srcml_1.1.0-1_ubuntu24.10_arm64.deb -n; \
    else \
        wget https://github.com/srcML/srcML/releases/download/v1.1.0/srcml_1.1.0-1_ubuntu24.04_amd64.deb && \
        gdebi srcml_1.1.0-1_ubuntu24.04_amd64.deb -n; \
    fi

# Install gumtree
COPY . /opt/gumtree
RUN /opt/gumtree/gradlew -PtestExternal -p /opt/gumtree build \
	&& ln -s /opt/gumtree/dist/build/install/gumtree/bin/gumtree /usr/bin/gumtree

# Define volume diff to make available files to diff
RUN mkdir -p /diff/left /diff/right
WORKDIR /diff
VOLUME /diff/left /diff/right

# Expose port 4567 for webdiff
EXPOSE 4567

ENTRYPOINT ["gumtree"]
