@startuml Core API
class Symbol {
}

class SymbolSet {
  + {static} Symbol symbol(String symbol);
}

interface Tree {
  + Node getRoot();
}

interface Node {
  + List<Node> getChildren();
  + Node getParent();
  + Symbol getSymbol();
  + String getLabel();
}

interface Matcher {
  + match(Tree src, Tree dst);
  + createMatcher(Tree src, Tree dst);
}

class MappingSet {
  + void map(Node src, Node dst);
  + boolean hasMapping(Node src, Node dst);
  + boolean hasMappingForSrc(Node src);
  + boolean hasMappingForDst(Node dst);
  + Node getMappedNodeForSrc(Node src);
  + Node getMappedNodeForDst(Node dst);
}

class Mapping {
  + Node getSrcNode();
  + Node getDstNode();
}

class Diff {
  + Tree getSrcTree();
  + Tree getDstTree();
  + MappingSet getMappings();
  + Script getScript();
}

class Script {

}

@enduml