name: Build and Test GumTree

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: "ci-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message || '', '[no ci]') && !startsWith(github.event.head_commit.message || '', 'doc') }}
    uses: ./.github/workflows/reusable-build.yml
    with:
      upload_distribution: false
    permissions:
      contents: read
